### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by KyleGaunt** [KyleGaunt/ContractInstructionModule#25]
The user interface will be designed using React Native and run using Expo.
This will provide a flexible design that will be compatible with Android, iOS and Desktop.

The following pages/screens will be created:

- [ ] Home
- [ ] Create New Contract Instruction
- [ ] My Profile
- [ ] Edit Contract Instruction
- [ ] View Contract Instruction
- [ ] Sign In
- [ ] Sign Up
- [ ] Forgot Password
